<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-05T13:47:20 IST" name="Suite" finished-at="2022-04-05T13:47:27 IST" duration-ms="6762">
    <groups>
    </groups>
    <test started-at="2022-04-05T13:47:20 IST" name="Test" finished-at="2022-04-05T13:47:27 IST" duration-ms="6762">
      <class name="maven1.Test1">
        <test-method is-config="true" signature="login()[pri:0, instance:maven1.Test1@a9cd3b1]" started-at="2022-04-05T13:47:09 IST" name="login" finished-at="2022-04-05T13:47:20 IST" duration-ms="11146" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="bclass()[pri:0, instance:maven1.Test1@a9cd3b1]" started-at="2022-04-05T13:47:20 IST" name="bclass" finished-at="2022-04-05T13:47:20 IST" duration-ms="85" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bclass -->
        <test-method signature="log()[pri:0, instance:maven1.Test1@a9cd3b1]" started-at="2022-04-05T13:47:20 IST" name="log" finished-at="2022-04-05T13:47:24 IST" duration-ms="4527" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- log -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:maven1.Test1@a9cd3b1]" started-at="2022-04-05T13:47:27 IST" name="teardown" finished-at="2022-04-05T13:47:27 IST" duration-ms="151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- maven1.Test1 -->
      <class name="maven1.Test2">
        <test-method is-config="true" signature="bclass()[pri:0, instance:maven1.Test2@9353778]" started-at="2022-04-05T13:47:24 IST" name="bclass" finished-at="2022-04-05T13:47:24 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bclass -->
        <test-method signature="hom()[pri:0, instance:maven1.Test2@9353778]" started-at="2022-04-05T13:47:24 IST" name="hom" finished-at="2022-04-05T13:47:24 IST" duration-ms="7" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at maven1.Test2.hom(Test2.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hom -->
      </class> <!-- maven1.Test2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
