<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-06T18:54:46 IST" name="Suite" finished-at="2022-04-06T18:54:49 IST" duration-ms="2900">
    <groups>
    </groups>
    <test started-at="2022-04-06T18:54:46 IST" name="Test" finished-at="2022-04-06T18:54:49 IST" duration-ms="2900">
      <class name="maven1.Test1">
        <test-method is-config="true" signature="login()[pri:0, instance:maven1.Test1@4567f35d]" started-at="2022-04-06T18:54:28 IST" name="login" finished-at="2022-04-06T18:54:46 IST" duration-ms="17823" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="bclass()[pri:0, instance:maven1.Test1@4567f35d]" started-at="2022-04-06T18:54:46 IST" name="bclass" finished-at="2022-04-06T18:54:46 IST" duration-ms="60" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bclass -->
        <test-method signature="log()[pri:0, instance:maven1.Test1@4567f35d]" started-at="2022-04-06T18:54:46 IST" name="log" finished-at="2022-04-06T18:54:49 IST" duration-ms="2362" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- log -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:maven1.Test1@4567f35d]" started-at="2022-04-06T18:54:49 IST" name="teardown" finished-at="2022-04-06T18:54:49 IST" duration-ms="209" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- maven1.Test1 -->
      <class name="maven1.Test2">
        <test-method is-config="true" signature="bclass()[pri:0, instance:maven1.Test2@6b927fb]" started-at="2022-04-06T18:54:49 IST" name="bclass" finished-at="2022-04-06T18:54:49 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bclass -->
        <test-method signature="hom()[pri:0, instance:maven1.Test2@6b927fb]" started-at="2022-04-06T18:54:49 IST" name="hom" finished-at="2022-04-06T18:54:49 IST" duration-ms="10" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at maven1.Test2.hom(Test2.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hom -->
      </class> <!-- maven1.Test2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
